# -*- coding: utf-8 -*-
"""dastboard_percobaan_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2AUx6g2doWhQsUraB8O80tyu-dwGySd
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# ==============================
# LOAD DATA
# ==============================

# NOTE: @st.cache_data is commented out because it requires a Streamlit app context
# and causes 'NoSessionContext' errors when running individual cells in Colab.
# Uncomment it when running as a full Streamlit application.
# @st.cache_data
def load_data_colab_compatible(): # Renamed to avoid conflict with potential original Streamlit context
    try:
        df = pd.read_excel("data_simulasi_50_siswa_20_soal.xlsx")
    except FileNotFoundError:
        # Print a warning since st.warning also requires a Streamlit context
        print("WARNING: File 'data_simulasi_50_siswa_20_soal.xlsx' not found. Generating a dummy DataFrame for testing.")

        num_students = 50
        num_questions = 20
        student_names = [f"Siswa {i+1}" for i in range(num_students)]

        # Generate random scores for 20 questions (e.g., 0-10)
        data = {f"Soal {i+1}": np.random.randint(0, 11, num_students) for i in range(num_questions)}
        df = pd.DataFrame(data)
        df.insert(0, "Nama", student_names) # Add a 'Nama' column

        # Calculate 'Total_Nilai' based on dummy data
        soal_cols = [col for col in df.columns if "Soal" in col]
        df["Total_Nilai"] = df[soal_cols].sum(axis=1)

    return df

df = load_data_colab_compatible()

# ==========================================================
# INPUT DATA
# ==========================================================
uploaded_file = st.file_uploader("Upload file Excel", type=["xlsx"])

if uploaded_file is None:
    st.warning("Silakan upload file Excel terlebih dahulu.")
    st.stop()

# ==========================================================
# MEMBACA DATA
# ==========================================================
try:
    df = pd.read_excel(uploaded_file)
    indikator = df.apply(pd.to_numeric, errors="coerce")
except Exception as e:
    st.error(f"Gagal membaca file: {e}")
    st.stop()

# memastikan numerik

# ==============================
# SIDEBAR
# ==============================

st.sidebar.title("Filter Data")

# Jika ada kolom kelas / jenis kelamin, bisa difilter
columns = df.columns.tolist()

selected_columns = st.sidebar.multiselect(
    "Pilih Kolom yang Ditampilkan",
    columns,
    default=columns
)

df_display = df[selected_columns]

# ==============================
# TITLE
# ==============================

st.title("📊 Dashboard Analisis Hasil Ujian Siswa")
st.markdown("Analisis lengkap berdasarkan data 50 siswa dan 20 soal")

# ==============================
# STATISTIK UMUM
# ==============================

st.subheader("📌 Ringkasan Statistik")

# Asumsikan ada kolom Total_Nilai
if "Total_Nilai" not in df.columns:
    soal_cols = [col for col in df.columns if "Soal" in col]
    df["Total_Nilai"] = df[soal_cols].sum(axis=1)

col1, col2, col3, col4 = st.columns(4)

col1.metric("Jumlah Siswa", len(df))
col2.metric("Rata-rata Nilai", round(df["Total_Nilai"].mean(), 2))
col3.metric("Nilai Tertinggi", df["Total_Nilai"].max())
col4.metric("Nilai Terendah", df["Total_Nilai"].min())

# ==============================
# DISTRIBUSI NILAI
# ==============================

st.subheader("📈 Distribusi Nilai")

if "Total_Nilai" in df.columns:
    fig, ax = plt.subplots()
    ax.hist(df["Total_Nilai"], bins=10)
    ax.set_title("Distribusi Total Nilai")
    ax.set_xlabel("Total Nilai")
    ax.set_ylabel("Jumlah Siswa")
    st.pyplot(fig)
else:
    st.warning("Kolom Total_Nilai tidak ditemukan")

# ==============================
# RATA-RATA PER SOAL
# ==============================

st.subheader("📊 Rata-rata Nilai Per Soal")

soal_cols = [col for col in df.columns if "Soal" in col]

if len(soal_cols) > 0:
    rata_soal = df[soal_cols].mean()

    fig2, ax2 = plt.subplots()
    ax2.bar(rata_soal.index, rata_soal.values)
    ax2.set_title("Rata-rata Nilai Tiap Soal")
    ax2.set_xlabel("Soal")
    ax2.set_ylabel("Rata-rata")
    plt.xticks(rotation=90)
    st.pyplot(fig2)

# ==============================
# ANALISIS KETUNTASAN
# ==============================

st.subheader("🎯 Analisis Ketuntasan")

kkm = st.slider("Tentukan Nilai KKM", 0, 100, 75)

df["Status"] = df["Total_Nilai"].apply(
    lambda x: "Tuntas" if x >= kkm else "Tidak Tuntas"
)

status_counts = df["Status"].value_counts()

fig3, ax3 = plt.subplots()
ax3.pie(status_counts.values, labels=status_counts.index, autopct="%1.1f%%")
ax3.set_title("Persentase Ketuntasan")
st.pyplot(fig3)

# ==============================
# RANKING SISWA
# ==============================

st.subheader("🏆 Ranking Siswa")

if "Nama" in df.columns:
    ranking = df.sort_values(by="Total_Nilai", ascending=False)
    ranking = ranking[["Nama", "Total_Nilai"]]
    ranking["Ranking"] = range(1, len(ranking) + 1)
    st.dataframe(ranking, use_container_width=True)

# ==============================
# DATA LENGKAP
# ==============================

st.subheader("📋 Data Lengkap")

st.dataframe(df_display, use_container_width=True)